---
language: python
python: "2.7"

# Use the new container infrastructure
sudo: false

services:
  - docker

# Install ansible
addons:
  apt:
    packages:
    - python-pip

before_install:
  - docker-compose --version
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-apt python-pycurl make

install:
  # Install ansible
  - pip install ansible ansible-lint

  # Check ansible version
  - ansible --version

 script:
  - make test

#notifications:
#  webhooks: https://galaxy.ansible.com/api/v1/notifications/
